// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQKgNATNBUlkswsU1H9nkFZb_29aRYfs',
    appId: '1:349582514364:web:46f2b19b5b55e20a1bd8b9',
    messagingSenderId: '349582514364',
    projectId: 'benimbg-dfc8b',
    authDomain: 'benimbg-dfc8b.firebaseapp.com',
    storageBucket: 'benimbg-dfc8b.firebasestorage.app',
    measurementId: 'G-0E0RHEGLYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChc_dPRxVp2kNo3HcOfSr40gQ6FIKtjy0',
    appId: '1:349582514364:android:8abcf6c2e13b97c11bd8b9',
    messagingSenderId: '349582514364',
    projectId: 'benimbg-dfc8b',
    storageBucket: 'benimbg-dfc8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0dY0RfRfHAimvSJ_E8lliuVRg2EOh7Ek',
    appId: '1:349582514364:ios:05c99fe337060bdc1bd8b9',
    messagingSenderId: '349582514364',
    projectId: 'benimbg-dfc8b',
    storageBucket: 'benimbg-dfc8b.firebasestorage.app',
    iosBundleId: 'com.mbg.cegra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0dY0RfRfHAimvSJ_E8lliuVRg2EOh7Ek',
    appId: '1:349582514364:ios:05c99fe337060bdc1bd8b9',
    messagingSenderId: '349582514364',
    projectId: 'benimbg-dfc8b',
    storageBucket: 'benimbg-dfc8b.firebasestorage.app',
    iosBundleId: 'com.mbg.cegra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjQKgNATNBUlkswsU1H9nkFZb_29aRYfs',
    appId: '1:349582514364:web:9723228d927e74091bd8b9',
    messagingSenderId: '349582514364',
    projectId: 'benimbg-dfc8b',
    authDomain: 'benimbg-dfc8b.firebaseapp.com',
    storageBucket: 'benimbg-dfc8b.firebasestorage.app',
    measurementId: 'G-NYHE8KLJJM',
  );
}
